### ISSUE TITLE
Daily Beast Articles Have Blank Screen

### ISSUE THREAD

**Issue by pjpreilly** [parrotgeek1/FirefoxLegacy#10]
Same on Legacy 68.12.0p2 on osx Lion 10.7.5 as **[HERE](https://www.reddit.com/r/waterfox/comments/kp5l8s/the_daily_beast_articles_display_then_vanish_on/)**.

**Comment by parrotgeek1** [comment]
Happening also on the original 68.12.0esr (Big Sur); therefore not a Legacy bug.
