### ISSUE TITLE
Netflix  not working on Mountain Lion on late 2006 Imac

### ISSUE THREAD

**Issue by xerman5** [parrotgeek1/FirefoxLegacy#11]
When I try to watch anything on netflix there is a message about a plugin that stopped functioning (it does not specify which one) and the website shows an error: Generally Netflix Error 101 or 102.

I have tried disabling the reproduction or DRM content with no success.

Any clues? Thanks!

**Comment by parrotgeek1** [comment]
As mentioned on the page, DRM content does not work in Firefox Legacy.
Netflix still supports Silverlight however, so you can install Silverlight
and use Netflix in a browser that still supports NPAPI plugins, such as
Firefox Legacy 52.

**Comment by xerman5** [comment]
Ok, will give it a try for sure. Thanks for the fast anwer and have a great day!
