### ISSUE TITLE
Imgur links load to an empty space (68.12.0esr)

### ISSUE THREAD

**Issue by scrutinizer11** [parrotgeek1/FirefoxLegacy#12]
Hello,

For some reason when I try to open an Imgur link (such as [This Imgur image](https://imgur.com/6Om2eMp)) I see only a blank space. I checked Imgur help, but nothing to suggest a viable solution. I restarted without add-ons, ad-blockers; same. Can it be a new incompatibility? 

Browser console shows the following:

**Errors**

`ReferenceError: "ResizeObserver is not defined"
    r https://s.imgur.com/desktop-assets/js/hiddenAlbum.0ba575624ec37fda8188.bundle.js:1
    Oi https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    Ba https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    bu https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    bc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    vc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    sc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    o https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    unstable_runWithPriority https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:23
    Ho https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    $o https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    Ko https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    lc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    notify https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    notifyNestedSubs https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    handleChangeWrapper https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    d https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    d https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:79
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:79
    Qi https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    o https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    ta https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    na https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    St https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Ct https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    bt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Ot https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    mt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    qe https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Me https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    ge https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    me https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    h https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    m https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    Pt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Pt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    v https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    Se https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Se https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    r https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    r https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    pt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    ht https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    c https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    s https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    default https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    u https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:47
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:47
    Ke https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    e https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    v https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    i https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    r https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:64
main.7b3311ea330bfcf559f5.js:87:82198`

`Unhandled promise rejection ReferenceError: "ResizeObserver is not defined"
    r https://s.imgur.com/desktop-assets/js/hiddenAlbum.0ba575624ec37fda8188.bundle.js:1
    Oi https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    Ba https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    bu https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    bc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    vc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    sc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    o https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    unstable_runWithPriority https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:23
    Ho https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    $o https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    Ko https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    lc https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:87
    notify https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    notifyNestedSubs https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    handleChangeWrapper https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    d https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    d https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:79
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:79
    Qi https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    o https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    ta https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    na https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    St https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Ct https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    bt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Ot https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    mt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    qe https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Me https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    ge https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    me https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    h https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    m https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    Pt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Pt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    v https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    Se https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    Se https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    r https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    r https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    pt https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    ht https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    c https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    s https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:28
    default https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:39
    u https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:47
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:47
    Ke https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    e https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    v https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    a https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    i https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:1
    r https://s.imgur.com/desktop-assets/js/main.7b3311ea330bfcf559f5.js:64
main.7b3311ea330bfcf559f5.js:28:71907`
**Warnings**:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.amplitude.com/. (Reason: CORS request did not succeed).`
`USP is not accessible 2 6Om2eMp:1:1633`

**Comment by parrotgeek1** [comment]
This appears to be a new incompatibility. According to Mozilla,
ResizeObserver was added in Firefox 69.

**Comment by parrotgeek1** [comment]
Actually it appears that Mozilla had implemented this API but it was only
enabled in nightly builds until Firefox 69. This means that I will be able
to enable it in the next version of Firefox Legacy 68! I will also
investigate whether this is true for any other APIs and enable them too.

**Comment by parrotgeek1** [comment]
Released Firefox Legacy 68.12.0p3 with support for this and many other newer APIs, hopefully improving compatibility with many websites.

**Comment by parrotgeek1** [comment]
@pjpreilly
