### ISSUE TITLE
New Version 69 for Lion?

### ISSUE THREAD

**Issue by pjpreilly** [parrotgeek1/FirefoxLegacy#2]
Will there be a v69 for Lion? Noticed this page does not render the map in v67 tested in safe mode also. TIA

https://www.accuweather.com/en/us/pennsylvania/weather-radar

**Comment by pjpreilly** [comment]
I suppose NOT!

**Comment by pjpreilly** [comment]
Looks like opengl/webgl is not working.

![2019-10-12 06 38 39 pm](https://user-images.githubusercontent.com/10430084/66708549-fc0d2600-ed1f-11e9-9bf4-4008f173aa9b.png)

**Comment by parrotgeek1** [comment]
I don't think WebGL ever worked on GMA 950/X3100.

I will investigate this issue and in the future I will update newer versions for Lion. I need to reimplement some APIs in order to do so.

**Comment by pjpreilly** [comment]
Thx, it's working well enough on Waterfox's current release to support the weather map I referenced in the OP.

**Comment by pjpreilly** [comment]
FYI .. This page has issues with rendering in Lion v67.0.4p1, nothing is displayed in Safe mode. Web Console reports errors. TIA

https://filterlists.com/

**Comment by pjpreilly** [comment]
[THIS](https://www.reddit.com/r/waterfox/comments/alt6pm/google_calendar_rendering/)
is also happening on Lion v67.0.4.

**Comment by pjpreilly** [comment]
As is **[THIS](https://github.com/MrAlex94/Waterfox/issues/1245)**

**Comment by grahamperrin** [comment]
> Waterfox's current release

Waterfox Classic, not Waterfox Current – yes?

**Comment by pjpreilly** [comment]
> > Waterfox's current release
> 
> Waterfox Classic, not Waterfox Current – yes?

also happening on Lion. Only CLASSIC has Lion support.

**Comment by pjpreilly** [comment]
also happening on Lion. Only CLASSIC has Lion support.

or Mountain Lion support for that matter so any talk of Waterfox Current with this project seems moot.

**Comment by pjpreilly** [comment]
New builds coming anytime soon? TIA

**Comment by pjpreilly** [comment]
Security risk NOW!

**Comment by parrotgeek1** [comment]
I am unable to get version 70 and newer to work on lion; they crash randomly and have strange UI issues. I might switch to 68 ESR

**Comment by pjpreilly** [comment]
ESR is probably THE WAY to go at this point for 10.7 as well as 10.8!

**Comment by parrotgeek1** [comment]
I have resolved the issues with 70.0 and newer on 10.8 and plan in the future to release the latest version for 10.8 and 68 ESR for 10.7.

**Comment by pjpreilly** [comment]
Nice!!!

**Comment by pjpreilly** [comment]
Any ETA at this point?

**Comment by pjpreilly** [comment]
parrotgeek1 reopened this yesterday
.... Why?

**Comment by parrotgeek1** [comment]
Version 71 and newer have mysterious rendering issues on even 10.8 and I have no idea why.

**Comment by parrotgeek1** [comment]
released FF Legacy 68.12esr for 10.7 and 10.8 https://parrotgeek.com/fxlegacy.html
