### ISSUE TITLE
Future Release?

### ISSUE THREAD

**Issue by pjpreilly** [parrotgeek1/FirefoxLegacy#3]
Future releases of the latest version for 10.8 and 68 ESR for 10.7 gonna happen imminently? TIA for guidance.

**Comment by pjpreilly** [comment]
Need help, Waterfox Classic is faltering for 10.7 & 10.8! tia

**Comment by pjpreilly** [comment]
https://github.com/MrAlex94/Waterfox/issues/1523

**Comment by pjpreilly** [comment]
Waterfox fails again:

Crashes on launch again..... Classic versions 2020.4 2020.5 & 2020.6 are unusable on osx Lion 10.7.5 as well as osx 10.8.5.

**Comment by parrotgeek1** [comment]
Did you see this build? https://github.com/MrAlex94/Waterfox/issues/1523#issuecomment-631658037

**Comment by pjpreilly** [comment]
> Did you see this build? [MrAlex94/Waterfox#1523 (comment)](https://github.com/MrAlex94/Waterfox/issues/1523#issuecomment-631658037)

I did, but it's seems to just be a test build. Not a maintained fork as far as I can tell.

**Comment by parrotgeek1** [comment]
released FF Legacy 68.12esr for 10.7 and 10.8 https://parrotgeek.com/fxlegacy.html
