### ISSUE TITLE
Weather Underground Dashboard Site Issue

### ISSUE THREAD

**Issue by pjpreilly** [parrotgeek1/FirefoxLegacy#7]
This local dashboard **[SITE](https://www.wunderground.com/dashboard/pws/KPACHELT4?cm_ven=localwx_pwsdash)** causes an inordinate amount of processor usage so much so the other tab playing audio freezes up. The map top right doesn't display correctly & I wouldn't be surprised if this is a contributing factor. Os x 10.7 version tested. TIA

**Comment by parrotgeek1** [comment]
Apologies for the delayed response; I don't know what could be causing this. The only thing I am familiar with is reimplementing APIs that 10.7/10.8 needs; I don't really have enough knowledge of FF internals to diagnose issues with individual sites sadly.

**Comment by parrotgeek1** [comment]
Can't reproduce this in 68.12.0p2 on MacBook4,1 Lion. 
The map loads for me, btw.

**Comment by pjpreilly** [comment]
The map loads but it renders incorrectly. Also looks like all the ads & junk consume the JS engine for a while saturating the processor for me. The ad blocker seems a bit overwhelmed too.

**Comment by parrotgeek1** [comment]
It might be rendering incorrectly because WebGL is broken on these old GPUs.
